Support IMDSv2
Shanon/s3get.sh pull request #9
Opened 2024-04-20 02:49 UTC by inomata-qa

Support IMDSv2.

AWS Doc
https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/instance-metadata-v2-how-it-works.html 

Test
S3 download can be confirmed in the following cases:
- Running on an instance with optional IMDSv2
- Running on an instance with mandatory IMDSv2
- Running on ECS with a task role

2024-04-25 11:51 UTC, shot056 requested changes
内容について1点と、
こちらは正直重要じゃないのですが、バージョンは `1.0.0` にしていただけると助かります。
`MAJOR`.`MINOR`.`PATCH` で、
`MAJOR`は互換性を保たないかもしれない修正
`MINOR`は互換性を保った機能追加等の修正
`PATCH`はバグフィックス
という風になっています。

いままでの僕の修正も適当に末尾を加算してた気はしますが；

2024-04-25 11:51 UTC, shot056 commented on s3get.sh
> +        ROLE_NAME=$(curl -L -H "X-aws-ec2-metadata-token: $METADATA_TOKEN" $_ROLE_URL --silent --connect-timeout 3 | grep '^[a-zA-Z0-9._-]\+$') && {
すみません こちらの `METADATA_TOKEN` ですが、
グローバル変数を経由するのではなく、
```sh
get_metadata_token() {
  v_msg "get metadata token"
  curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60"
}
....
  METADATA_TOKEN=$(get_metadata_token)
```

というように関数の出力として取るようにしてもらえると助かります

2024-04-26 01:36 UTC, inomata-qa commented
指摘部分の対応をしました。

2024-04-26 03:05 UTC, shot056 approved these changes

2024-04-26 03:05 UTC, merged